### ISSUE TITLE
Cannot test take(1) subscription

### ISSUE THREAD

**Issue by regexer-github** [meltedspark/jest-marbles#114]
I'm trying to write a test to enforce a take(1) on an observable.

``` javascript
marbles(m => {
                // Arrange
                component.observable$ = m.cold('x', { x: 'value'});
                // Act
                component.clickEvent();
                // Assert
                m.expect(component.observable$).toHaveSubscriptions('^');
            })
```
Inside the clickEvent: 
`this.observable$.pipe(take(1)).subscribe(o => { // Do some logic with o});`

The problem is, a take(1) expects the following subscription: 
`{"subscribedFrame":0,"unsubscribedFrame":0}`. 
Whereas the toHaveSubscriptions syntax does not support this (since every character represents a frame).

So, when I write
`m.expect(component.$).toHaveSubscriptions('^');`
I get
`{"subscribedFrame":0,"unsubscribedFrame":null}`

When I write
`m.expect(component.$).toHaveSubscriptions('!');`
I get
`{"subscribedFrame":null, "unsubscribedFrame":0}`

When I write
`m.expect(component.$).toHaveSubscriptions('^!');`
I get
`{"subscribedFrame":0, "unsubscribedFrame":1}`

And if I write
`m.expect(component.$).toHaveSubscriptions(['^', '!']);`
I get
`{"subscribedFrame":0,"unsubscribedFrame":null}`
`{"subscribedFrame":null, "unsubscribedFrame":0}`

Any ideas how I could handle this?

**Comment by meltedspark** [comment]
I'm not sure that you're actually using `jest-marbles` because the syntax looks like syntax of `rxjs-marbles`. 
I'll try to help you anyways. As far as I understand you'd like to make sure that the observable inside the component takes 1 from the given observable and finishes.
So essentially what you really want to provide as an input observable is something that emits more than once.  
Also, pay attention that when you pipe an observable you get a new observable, which means you test basically tests the wrong one. What you rally want to test is the piped observable, while you're testing the original. 
If I was writing a test for this use case I'd probably do something like that:

```js
//inside the component
//the observable that you receive from a service function I guess, I put it here just to emphasize the difference between this o e and the tested
serviceObservable$; 
... //your code
//somewhere in your code where you subscribe
this.observable$ = thus.myservice$.pipe(take(1));
this.observable$.subscribe(o => {
//do something
} );

//test
const service = cold('a-b|');
component.myservice$ = service; //just for example, probably you have to mock your service method and return this observable from the mock
component.clickEvent();
expect(component.myservice$).toBeMarble('a|') //make sure it took 1 and unsubscribed
```

**Comment by meltedspark** [comment]
You can find a good example of full marble test (with services, mocks and stuff) [here](https://github.com/meltedspark/rxjs-marble-testing-tutorial/blob/solution/src/app/permissions.service.spec.ts). It is outdated in terms of Angular version but the concept stays the same.

**Comment by regexer-github** [comment]
... no clue how I messed up the library, as it's mentioned in my import. 
Thanks for your reply
